services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: ApplicationDB
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    name:  tp1_nest
    driver: local