services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: ApplicationDB
    ports:
      - "5435:5432"
    volumes:
      - data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:mysecurepassword@db:5432/ApplicationDB
      JWT_SECRET: strong_jwt_secret_token
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  studio:
    image: node:18
    container_name: prisma-studio
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    command: sh -c "npm install && npx prisma studio"
    environment:
      DATABASE_URL: postgres://postgres:mysecurepassword@db:5432/ApplicationDB
    depends_on:
      - db

volumes:
  data:
    name: tp1_nest
    driver: local
  redis_data:
    name: tp1_redis
    driver: local